version: "3.8"
services:
  agltct:
    container_name: agltct
    image: maven:3.8-eclipse-temurin-19-alpine
    working_dir: /app
    entrypoint: mvn spring-boot:run -Dmaven.repo.local=repository -DskipTests
    ports:
      - "8888:8888"
    volumes:
      - .:/app